### ISSUE TITLE
MP.jar file

### ISSUE THREAD

**Issue by kwells4** [MatthieuPalayret/DynMorpho_Analysis#1]
This looks like a great package and we would be very enthusiastic to use it. I was looking at the documentation and I saw that I need to add the MP.jar and Flanagan.jar files into the plugins folder within Fiji; however, I was only able to find the Flanagan.jar file in this repo.

Would you be able to share the MP.jar file or provide instructions on compiling the MP.jar file from this repo?

Thanks!
Kristen

**Comment by MatthieuPalayret** [comment]
Dear Kristen,
Thank you for your interest.
I have just added the missing "MP_.jar" file in the main folder. You can just download it and add it to the "plugins" folder in Fiji (you even may not need to add "Flanagan.jar").
Let me know if you have any other difficulties using this package.
Best!
Matthieu

**Comment by kwells4** [comment]
Thanks so much Matthieu, that's exactly what we needed!
